name: Publish

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Release type"
        required: true
        type: choice
        default: prerelease
        options: [prerelease, patch, minor, major]

permissions:
  contents: write
  id-token: write

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

      - name: Run tests
        run: npm run test:run

      - name: Build
        run: npm run build

      - name: Test build output
        run: |
          # Check ESM files
          test -f dist/pyret.js
          test -f dist/api.js
          test -f dist/default-rpcs.js
          # Check CommonJS files
          test -f dist/pyret.cjs
          test -f dist/api.cjs
          test -f dist/default-rpcs.cjs
          # Check TypeScript declaration files
          test -f dist/pyret.d.ts
          test -f dist/api.d.ts
          test -f dist/default-rpcs.d.ts
          echo "Build artifacts verified ✓"

      - name: Bump version
        id: bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ "${{ github.event.inputs.type }}" = "prerelease" ]; then
            npm version prerelease --preid=pre -m "release: %s"
            echo "tag=pre" >> $GITHUB_OUTPUT
          else
            npm version "${{ github.event.inputs.type }}" -m "release: %s"
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        run: git push --follow-tags

      - name: Publish to npm
        run: npm publish --access public --provenance --tag "${{ steps.bump.outputs.tag }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
